version: '3.8'

networks:
  my-postgres-network:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres  # Adjust username if needed
      - POSTGRES_PASSWORD=postgres  # Adjust password for security
    ports:
      - "5432:5432"  # Optional: Map container port to host port for easier access (not required)
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent storage for data
      - ./caravan.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql script
    networks:
      - my-postgres-network

volumes:
  postgres-data: {}
