# Generated by Django 3.2.5 on 2024-06-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingarea', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
