# Generated by Django 3.2.5 on 2024-06-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingarea', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
