# Generated by Django 3.2.5 on 2024-06-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingarea', '0007_alter_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
