# Generated by Django 3.2.5 on 2024-06-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingarea', '0010_userpreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
