# Generated by Django 3.2.5 on 2024-05-25 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True)),
                ('thumbnail', models.ImageField(default='parkingareas/default.jpg', upload_to='thumbnails')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('rental_start', models.DateTimeField()),
                ('rental_end', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('available', models.BooleanField()),
                ('contact', models.TextField()),
                ('address', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parking_areas',
                                             to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='parkingarea.Tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
